runtime: python37
service: thangs-react

instance_class: F1
automatic_scaling:
  min_instances: 1
  # TODO: Configure min_idle_instances if we need idle instances handy to scale.
  # min_idle_instances: ...

handlers:
  - url: /static/(.*)
    static_files: build/static/\1
    upload: build/static/(.*)
  - url: /vendors/(.*)
    static_files: build/vendors/\1
    upload: build/vendors/(.*)
  - url: /(manifest.json)
    static_files: build/\1
    upload: build/manifest.json
  - url: /(.*)\.ico
    static_files: build/\1.ico
    upload: build/(.*).ico
  - url: /(.*)\.png
    static_files: build/\1.png
    upload: build/(.*).png
  - url: /(info.html)
    static_files: build/\1
    upload: build/info.html
    expiration: 1s
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    expiration: 1m
    secure: always
