version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  test-in-staging:
    docker:
      - image: 'cypress/browsers:node12.4.0-chrome76'
        auth:
          username: ${DOCKER_HUB_ID}
          password: ${DOCKER_HUB_PWD}
    environment:
        REACT_APP_API_KEY: 'https://staging-api-platform-dot-gcp-and-physna.uc.r.appspot.com/'
workflows:
  version: 2
  run-tests:
    jobs:
      - cypress/run:
          executor: test-in-staging
          context: physna-web
          yarn: true
          start: yarn dev
          wait-on: 'http://localhost:3000'
          store_artifacts: true
          browser: chrome
          verify-command: yarn cypress verify
