version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  version: 2
  run-tests:
    jobs:
      - cypress/run:
          yarn: true
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          verify-command: yarn cypress verify
          start: yarn run dev
          wait-on: 'http://localhost:3000'