version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  version: 2
  run-tests:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn dev
          wait-on: 'http://localhost:3000'
          executor: cypress/base-14
          browser: chrome
          verify-command: yarn cypress verify
