version: 2.1
jobs:
  deploy:
    parameters:
      NoPromote:
        default: "--no-promote"
        type: string
      Version:
        default: ""
        type: string
        description: "add --version someVersionName if you want to assign a version"
      Stack:
        default: ${CIRCLE_BRANCH}
        type: string
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile
      - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
      - run:
        # Build staging release
        # TODO: This needs to be pulled into a separate job & workflow so that
        #       we can run staging steps in the deploy-staging workflow and
        #       production steps in the deploy-production workflow.
        yarn build:staging
      - run: |
          # Store service account
          echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
          # Initialize gcloud CLI
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud app deploy --quiet <<parameters.Stack>>.yaml <<parameters.NoPromote>> <<parameters.Version>>
workflows:
  version: 2
  deploy-gcloud:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleci-setup