export { default as Landing } from './Landing'
export * from './Login'
export * from './Signup'
export * from './Profile'
export * from './Model'
export * from './SearchResults'
export * from './PasswordReset'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export * from './TermsAndConditions'
export * from './404'
