import {
    OFF_WHITE,
    GREY_1,
    GREY_3,
    GREY_4,
    GREY_5,
    GREY_6,
    GREY_7,
    GREY_8,
    GREY_9,
    GREY_10,
    BLACK_1,
    BLACK_2,
    BLACK_3,
    BLACK_4,
    BLACK_5,
    YELLOW_1,
    BLUE_1,
    BLUE_2,
    BLUE_3,
    BROWN,
    RED_1,
    RED_4,
    WHITE_1,
    WHITE_2,
    WHITE_3,
    WHITE_4,
    LIGHT_PURPLE,
} from './colors';
import {
    modelCardHoverText,
    flashToastText,
    zeroStateText,
    bodyCopyText,
    tabNavigationText,
    cardNumbersText,
    formCalloutText,
    usernameText,
    subheaderText,
    modelTitleText as _modelTitleText,
    pageTitleText,
    usernameLinkText,
    headerText,
    logoText as _logoText,
} from './text';

/*
 * These will be the fonts we actually want to use, but we need to get them from
 * our designer before we can use them.
 */
const fontMedium = "'Montserrat', sans-serif";
const fontMain = "'Montserrat', sans-serif";
const shadow = 'box-shadow: 0px 5px 10px 0px rgba(35, 37, 48, 0.25)';
const headerFont = 'Lexend Deca';

const maxWidth = '1237px;';

export const NewTheme = {
    activityCount: GREY_3,
    avatarInitialsColor: GREY_10,
    avatarTextColor: GREY_1,
    backgroundColor: GREY_8,
    brandColor: YELLOW_1,
    buttonFont: fontMedium,
    buttonShadow: 'inset 0 0 0 2px #FFFFFF',
    cardBackground: WHITE_1,
    cardHeartColor: BLUE_2,
    deleteButton: GREY_7,
    dropdownTextColor: OFF_WHITE,
    dropdownBackgroundColor: GREY_7,
    errorTextColor: RED_4,
    errorTextBackground: RED_1,
    emptyImageBackground: GREY_7,
    flashColor: GREY_5,
    flashColorText: WHITE_3,
    formLabelColor: GREY_4,
    imagePlaceholderText: GREY_3,
    invertedHeaderBackground: BLACK_2,
    headerFont,
    headerColor: BLACK_3,
    headerColorOnDarkBackground: WHITE_1,
    linkText: BLUE_2,
    linkTextVisited: BLUE_3,
    logoText: BLACK_4,
    mainFont: fontMain,
    mainFontColor: BLACK_5,
    matchingSubheaderColor: BLACK_1,
    maxWidth,
    modelActionButtonBackground: GREY_3,
    modelActionButtonText: WHITE_1,
    modelDetailLabel: GREY_5,
    modelOwnerLink: BLUE_2,
    modelPrimaryButtonBackground: BLUE_2,
    modelPrimaryButtonText: WHITE_2,
    modelTitleText: BLACK_1,
    modelViewerPlaceholder: OFF_WHITE,
    primaryButton: BLUE_2,
    primaryButtonText: WHITE_2,
    primaryButtonDisabledColor: GREY_9,
    profileContentColor: BLACK_5,
    profileNameColor: BLACK_5,
    promotionalSecondaryTextColor: GREY_3,
    promotionalTextColor: WHITE_1,
    searchBackground: WHITE_1,
    searchIconColor: GREY_5,
    searchText: GREY_4,
    secondaryButton: GREY_9,
    secondaryButtonText: WHITE_1,
    selectedProfileTabColor: BLACK_1,
    shadow,
    textColorOnDarkBackground: GREY_4,
    textOnBrandColor: BROWN,
    textInputBackground: OFF_WHITE,
    textInputColor: BLACK_1,
    textInputPlaceholderColor: GREY_4,
    unselectedProfileTabColor: GREY_5,
    uploaderBackground: BLACK_2,
    uploaderBackgroundActive: BLACK_4,
    uploaderText: GREY_3,
    viewerText: GREY_6,
    viewerTitle: BLACK_1,
    viewerExitColor: BLACK_3,
    viewerControlBorderColor: GREY_1,
    viewerControlText: GREY_4,
    zeroStateColor: GREY_6,
    zeroStateBackground: GREY_1,
    modelCardHoverText,
    flashToastText,
    zeroStateText,
    bodyCopyText,
    tabNavigationText,
    cardNumbersText,
    formCalloutText,
    usernameText,
    subheaderText,
    _modelTitleText,
    pageTitleText,
    usernameLinkText,
    headerText,
    _logoText,
};

export const NewDarkTheme = {
    ...NewTheme,
    backgroundColor: BLACK_2,
    linkText: BLUE_1,
    linkTextVisited: LIGHT_PURPLE,
    mainFontColor: GREY_4,
    textInputBackground: WHITE_4,
};
