name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1.1.0
    - run: yarn test --passWithNoTests
      env:
        CI: true
    - name: Cypress.io
      uses: cypress-io/github-action@v1.16.1
      with:
        start: yarn start
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-videos
        path: cypress/videos
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
