name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1.1.0
    - run: yarn test --passWithNoTests
      env:
        CI: true
    - name: Cypress.io
      uses: cypress-io/github-action@v1.16.1
